USE DATABASE ZOMATO;
USE SCHEMA ZOMATO.RAW;

CREATE OR REPLACE FILE FORMAT ZOMATO.RAW.CSV_FORMAT
  TYPE='CSV'
  FIELD_DELIMITER = ','
  COMPRESSION = 'AUTO'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  EMPTY_FIELD_AS_NULL = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

  CREATE OR REPLACE STAGE ZOMATO.RAW.ZOMATO_RAW_STAGE
  STORAGE_INTEGRATION = ZOMATO_S3
  URL = 's3://food-delivery-pipe-bronze/data/'
  FILE_FORMAT = ZOMATO.RAW.CSV_FORMAT

  LIST @ZOMATO.RAW.ZOMATO_RAW_STAGE