CREATE OR REPLACE STORAGE INTEGRATION ZOMATO_S3
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::894347067625:role/s3_snowflake_access'
  STORAGE_ALLOWED_LOCATIONS =('s3://food-delivery-pipe-bronze/')
  ENABLED = true;

  DESC INTEGRATION ZOMATO_S3;